version: '3.8'
services:
  app: 
    build: .
    ports: 
      - 8888:8888
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    # Enable ports for outside access
    # ports:
    #   - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=winning_eve
